# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

# Copy all project files
COPY . .

# Upgrade pip and install necessary dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir "mcp[cli]>=1.5.0" requests

CMD ["python", "collect.py"]
